import "../styles/styles.scss";
import Head from "next/head";
import type { AppProps } from "next/app";
import Header from "./components/layout/Header/index";

const MyApp: React.FC<AppProps> = ({ Component, pageProps }) => {
  return (
    <div className="root-app">
      <Head>
        <title>hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
      {/* <Header /> */}
    </div>
  );
};

export default MyApp;
