import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header/index";
import Home from "./components/features/Home/index";

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>
      <Header />
      <main className="page-main">
        <Home />
      </main>
      <Footer />
    </>
  );
};

export default HomePage;
